### ISSUE TITLE
Cannot create META file for findlib packages with multiple roots

### ISSUE THREAD

**Issue by copy** [solvuu/solvuu-build#53] opened 2017-01-13 17:19 UTC
Test case below:

```ocaml
open Solvuu_build.Std

let lib1 = Project.lib "test_lib1"
    ~dir:"lib1"
    ~style:`Basic
    ~pkg:"test_lib1"

let lib2 = Project.lib "test_lib2"
    ~dir:"lib2"
    ~style:`Basic
    ~pkg:"test_lib2"

let () = Project.basic1 ~project_name:"test" ~version:"dev" [lib1; lib2]
```

Probably related to #35, since in this case I don't want to create findlib packages (and therefore don't care about the META file), only internal libraries.

**Comment by agarwal** [comment] 2017-01-13 17:53
I'll close this as a duplicate of #35. If you really have libs like this _and_ want to install them with findlib, we'd need to create multiple META files. Let me know if that ends up being a need.

**Closed by agarwal** 2017-01-13 17:53 UTC

**Comment by copy** [comment] 2017-01-13 19:42
As a workaround, one can use a structure like in [biocaml's myocamlbuild](https://github.com/biocaml/biocaml/blob/master/myocamlbuild.ml).

**Comment by agarwal** [comment] 2017-01-13 20:02
Do you mean you can avoid calling the high level function `Project.basic1`? Indeed, that is the recommended way of customizing the build. `Project.basic1` isn't meant to handle all use cases, though it does turn out to be sufficient pretty often.

**Comment by copy** [comment] 2017-01-14 01:10
Yep, this way works well for my (relatively complex) project.

**Comment by smondet** [comment] 2017-04-19 20:18
*I didn't go through with it but the discussion may be interesting.*

I tried to create two separate `META` files for 2 libraries in the same repo
instead of a single `_build/META` file with sub-libraries.
(having `lib_one` + `lib_two` seems more future-friendly to me than `lib.one` + `lib.two`)

I tried with my own replacement of `Project.basic1`:

```ocaml
  let open Solvuu_build.Std.Project in
  (* Compute graph to check for cycles and other errors. *)
  ignore (Graph.of_list items);
  Ocamlbuild_plugin.dispatch @@ begin function
  | Ocamlbuild_plugin.After_rules -> (
(* ... *)
```

using the `~prod` argument of `Findlib.build_meta_file` and such.

The problem is that the assumption of one single `META` is used a bit too often
to make this really practical, it shows up e.g. in:

- `build_static_file "project.mk" (fun () -> makefile items ~project_name);`
- `build_static_file (sprintf "%s.install" project_name) (fun () -> install_file items);`
- etc.

**Comment by agarwal** [comment] 2017-04-19 21:00
For `Project.makefile`, the rule to build a META file is not needed and already deprecated. We can just remove it.

For the install file, we could break up the implementation of `Project.install_file` into smaller functions, which build up just the lines for a lib, an app, etc. You could then use these to create your own `.install` file in a more customized fashion. I've created #68 to track this request.
